In [1]:
import numpy as np

In [4]:
x = np.matrix([1, 2, 3, 4]).T
x

matrix([[1],
        [2],
        [3],
        [4]])

In [5]:
x - x.T

matrix([[ 0, -1, -2, -3],
        [ 1,  0, -1, -2],
        [ 2,  1,  0, -1],
        [ 3,  2,  1,  0]])

In [6]:
np.abs(x - x.T)

matrix([[0, 1, 2, 3],
        [1, 0, 1, 2],
        [2, 1, 0, 1],
        [3, 2, 1, 0]])

In [7]:
np.sum(np.abs(x - x.T)) / (2 * len(x) * np.sum(np.abs(x)))

0.25